<?php

function block_weather_block_info() {
    $blocs['block_weather'] = array(
        'info'  => "Block_weather",
        'cache' => DRUPAL_NO_CACHE,
    );
    return $blocs;
}
function block_weather_block_view($delta = '') {
    switch($delta){
        case 'block_weather':
            $weather= weather_get_weather();
            $city=variable_get('city');
            $block['subject'] = 'Погода '.$city;
            $block['content'] = '<img src="http://img.yandex.net/i/wiz' . $weather['image'] .'.png" alt="' . $weather['type'] . '" />
        ' . ($weather['temperature'] > 0 ? '+' . $weather['temperature'] : $weather['temperature']) .'
        ' . $weather['type'];
            break;
    }
    return $block;
}
function weather_get_weather ($ignore_cache = FALSE) {
    if (!$ignore_cache && ($cache = cache_get('weather'))) {
        $weather = $cache->data;
    }
    else {
        $xml = simplexml_load_file('http://export.yandex.ru/weather-ng/forecasts/33487.xml');
        $weather = array(
            'temperature'=> (string)$xml->fact->temperature,
            'image'      => (string)$xml->fact->image,
            'type'       => (string)$xml->fact->weather_type,
        );
        cache_set('weather', $weather);
        variable_set('weather_update_time', REQUEST_TIME);
    }
    return $weather;
}
function weather_cron() {
    if (REQUEST_TIME - variable_get('weather_update_time', 0) >= 60*60) {
        weather_get_weather(TRUE);
    }
}
function block_weather_menu() {
    $items = array();
    $items['admin/structure/block_weather']=array(
        'title'=>'Weather',
        'page callback'=>'drupal_get_form',
        'page arguments' => array('weather_form'),
        'access callback' => TRUE,
        'type'=> MENU_NORMAL_ITEM,

    );
    return $items;
}
function weather_form($form,&$form_state){
    $form = array();
    $form['city']= array (
        '#type' => 'textfield',
        '#title' => t('Введіть місто'),
        '#default_value' => variable_get('city'),
    );
    $form['submit']= array(
        '#type'=>'submit',
        '#value'=>t('Submit'),
    );
    return $form;
}
function main_function(){
    $form = drupal_get_form('weather_form'); //отримуєм поля форми
    $form = drupal_render($form); //рендерим форму
    return $form.'Додатковий текст.';
}

function weather_form_submit($form,&$form_state){

    variable_set('city',$form_state['values']['city']);

}